### ISSUE TITLE
Unknown error 524 and no logs

### ISSUE THREAD

**Issue by martinclauss** [aya-rs/book#106]
Hey!

I tried the example from here: https://aya-rs.dev/book/start/hello-xdp/

When I run `cargo xtask run -- -i enp1s0` nothing happens (there should be some `info!()` messages...

```
$ ip a show enp1s0
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 xdp/id:50 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:16:3f:54 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.26/24 brd 192.168.122.255 scope global dynamic noprefixroute enp1s0
       valid_lft 3197sec preferred_lft 3197sec
    inet6 fe80::99c0:834f:c1be:47f5/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

```
$ sudo bpftool prog show id 50
50: xdp  name xdp  tag c647997d837a969d  gpl
	loaded_at 2023-03-08T15:16:46+0100  uid 0
	xlated 1944B  jited 1100B  memlock 4096B  map_ids 25,24,23
```

When I look at the maps:

```
$ sudo bpftool map | rg -i aya
23: perf_event_array  name AYA_LOGS  flags 0x0
25: percpu_array  name AYA_LOG_BUF  flags 0x0
```

```
$ sudo bpftool map dump name AYA_LOGS
key:
00 00 00 00
value:
Unknown error 524
key:
01 00 00 00
value:
Unknown error 524
key:
02 00 00 00
value:
Unknown error 524
key:
03 00 00 00
value:
Unknown error 524
key:
04 00 00 00
value:
Unknown error 524
key:
05 00 00 00
value:
Unknown error 524
key:
06 00 00 00
value:
Unknown error 524
key:
07 00 00 00
value:
Unknown error 524
key:
08 00 00 00
value:
Unknown error 524
key:
09 00 00 00
value:
Unknown error 524
Found 0 elements
```

Same behavior with kernels `6.2.0-1-MANJARO` (Manjaro) and `6.1.14-200.fc37.x86_64` (Fedora)

It worked before... but somehow not anymore...

Thanks!
Martin

**Comment by martinclauss** [comment]
I also ran this example program and it works without any problem: https://github.com/libbpf/libbpf-bootstrap/tree/master/examples/rust/xdp

**Comment by martinclauss** [comment]
Hey! :) I also tried a recent Kali Linux, but the problem persists... Any ideas?

Thanks!

**Comment by flz** [comment]
Maybe you found out what was wrong since you posted but I wasted about an hour trying to figure out why I was getting "unknown error 524" in the logs map and no output from the userland program.

I don't know what error 524 in this case (Google tells me it's ENOTSUPP) but I eventually found out that I wasn't getting log messages because I needed to adjust RUST_LOG (try setting to debug).
