### ISSUE TITLE
add cross-compilation instructions - initially for a Mac

### ISSUE THREAD

**Issue by dmitris** [aya-rs/book#107]
add cross-compilation instructions to the book along the lines of https://github.com/dmitris/tcbpftest#cross-compilation

**Comment by sanmai-NL** [comment]
@dmitris This seems to have been completed in the meantime. 
https://aya-rs.dev/book/aya/crosscompile/
Can you close, if true?

**Comment by dmitris** [comment]
Done in https://github.com/aya-rs/book/pull/132 and https://github.com/aya-rs/book/pull/139.
