### ISSUE TITLE
Invalid argument (os error 22) on attach, classifier program

### ISSUE THREAD

**Issue by emanuele-em** [aya-rs/book#143]
On this line
```
    program.attach(&opt.iface, TcAttachType::Egress)?; //&opt.iface = wlo1
```
the program always return:

> Error: netlink error while attaching ebpf program to tc
> Caused by:
> Invalid argument (os error 22)

I'm using _Arch linux_ with _kernel version 6.6.6-arch1-1_
Rust version is _1.75 stable_

p.s. other programs like XDP correctly compile and run

**Comment by alessandrod** [comment]
Can you run your program under strace -e trace=network -s10000000 and attach the output?
