### ISSUE TITLE
SSL_ERROR_UNRECOGNIZED_NAME_ALERT when accessing your website

### ISSUE THREAD

**Issue by gallexis** [aya-rs/book#158]
There is a **SSL_ERROR_UNRECOGNIZED_NAME_ALERT** error when trying to access https://aya-rs.dev/book/

**Comment by dave-tucker** [comment]
Thanks for reporting this. The domain expired, but it's been renewed now. I can confirm that this is now fixed for me and I expect it will be resolved for everyone else in the next hour or so while DNS servers get updated.
