### ISSUE TITLE
build: failure in `Check Examples` from #825 

### ISSUE THREAD

**Issue by yskelg** [aya-rs/book#162]
There are build failure issue.
- https://github.com/aya-rs/book/actions/runs/10295865237/job/28503255247
```
error: "/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
thread 'main' panicked at xtask/src/build_ebpf.rs:65:5:
assertion failed: status.success()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Process completed with exit code 101.
```

**Comment by tyrone-wu** [comment]
A fix was just pushed yesterday https://github.com/rust-lang/cargo/pull/14370, so the issue should be resolved in the next nightly.

**Comment by yskelg** [comment]
Thank you @tyrone-wu , I checked the build success after [#827](https://github.com/aya-rs/book/actions/runs/10328898318) build.

Close this issue.
