### ISSUE TITLE
book need to update accroding to the template build command change 

### ISSUE THREAD

**Issue by dassio** [aya-rs/book#176]
the recent template commit: https://github.com/aya-rs/aya-template/commit/5811d6ff5687ae115cc8876ddf511dd01c02539b make the [getting started guide](https://aya-rs.dev/book/start/hello-xdp/#prerequisites) command `cargo xtask build-ebpf` not working.
need to update the book and example code  to reflect this change.

the build and running command should be:
```
cargo build 

RUST_LOG=info cargo run -- --iface enp5s0

```

**Comment by tamird** [comment]
Can you send a pull request?

**Comment by tamird** [comment]
Note that the book doesn't mention the template so it is technically not broken. But we should update the book examples to the latest template.\
