### ISSUE TITLE
A "-" in xdp name leads to os error 22

### ISSUE THREAD

**Issue by jornfranke** [aya-rs/book#53]
If I replace the xpd name found in https://github.com/aya-rs/book/blob/main/examples/myapp-01/myapp-ebpf/src/main.rs#L11 with a name containing a "-" and adapting it https://github.com/aya-rs/book/blob/main/examples/myapp-01/myapp/src/main.rs#L46 then I get when running the program:
```
Error: the BPF_PROG_LOAD syscall failed. Verifier output: 

Caused by:
    Invalid argument (os error 22)
```
For example, I replaced "myapp" with "localnet-filter". After changing it to "localnetfilter" it works.

Probably one should adapt the attribute "#xdp" to check for invalid characters and throw an error at compile time. 

Btw. is my assumption correct that only alphanumerical characters are allowed for the name?

**Comment by dave-tucker** [comment]
Hey @jornfranke thanks for reporting this issue.

> Btw. is my assumption correct that only alphanumerical characters are allowed for the name?

That is correct.

I'll go ahead and close this here as we'll be revisiting program name handling in https://github.com/aya-rs/aya/issues/375
