### ISSUE TITLE
Book describes a code which was deleted

### ISSUE THREAD

**Issue by pooladkhay** [aya-rs/book#85]
Hi,

https://github.com/aya-rs/book/blob/main/docs/book/start/logging-packets.md

The book describes how to exchange data between user-space and kernel-space using `PerfEventArray` while the code for that has been deleted: https://github.com/aya-rs/book/commit/1c6344087e8a5fce0a8294538bef76e967817c28#diff-c94c93586689a4b5143213b53901e407386b7df3cfc090996226685e3a1693e9L52

**Comment by vadorovsky** [comment]
Whoops, sorry for that!

I will remove the `PerfEventArray` descriptions from that page and provide some other, better example for using perf buffers.

**Comment by vadorovsky** [comment]
It's done
